Solution
mate-academy/react_films-list-use-raw-redux pull request #21
Opened 2019-10-09 13:23 UTC by amserhii11

https://amserhii11.github.io/react_films-list-use-raw-redux/

2019-10-09 13:29 UTC, amserhii11 commented
Не розумію чому, на якомусь етапі перестало додавати нове, і дефолтна картка теж зникла

2019-10-09 14:19 UTC, YuriiHoliuk commented on src/App.js
> +          Title, Plot, Poster, Website, imdbID,
Title,
          Plot,
          Poster,
          Website,
          imdbID,

2019-10-09 15:05 UTC, irenhh requested changes
your page doesn't work, check gh-pages and console after deployment

2019-10-09 15:05 UTC, irenhh commented on src/App.js
>  const API_URL = 'http://www.omdbapi.com/?apikey=2f4a38c9&t=';
https

2019-10-15 12:16 UTC, danheim commented
Добавление фильма по поиску не работает, как и обычное

2019-10-16 08:18 UTC, danheim approved these changes
Мне нравится, все работает. Несколько мелких замечаний только, прими к сведению.

2019-10-16 08:18 UTC, danheim commented on src/App.js
> +      <BrowserRouter basename={process.env.PUBLIC_URL}>
like

2019-10-16 08:18 UTC, danheim commented on src/App.js
> +          Title, Plot, Poster, Website, imdbID,
замечание Юры не исправлено

2025-09-02 14:29 UTC, closed without merging