Solution
mate-academy/react_films-list-use-raw-redux pull request #6
Opened 2019-10-01 21:38 UTC by KosBelozyorov

[DEMO LINK](https://kosbelozyorov.github.io/react_films-list-use-raw-redux/)

2019-10-02 06:00 UTC, YuriiHoliuk requested changes

2019-10-02 06:00 UTC, YuriiHoliuk commented on src/App.js
> +      .subscribe(() => this.setState());
Why do you set empty state?

2019-10-02 06:00 UTC, YuriiHoliuk commented on src/components/FilmDetails/FilmDetails.js
> +      this.forceUpdate();
do not use forceUpdate

2019-10-02 06:00 UTC, YuriiHoliuk commented on src/App.js
> +      .subscribe(() => this.setState());
Why do you need store subscription here

2019-10-02 06:00 UTC, YuriiHoliuk commented on src/components/FilmDetails/FilmDetails.js
> +      .films.find(film => film.id === this.props.match.params.id),
what if url will change? Your component always show the same film

2019-10-03 08:51 UTC, KosBelozyorov commented
fixed

2019-10-03 14:30 UTC, danheim approved these changes
good

2025-09-21 20:36 UTC, closed without merging